name: CI
on:
  push:
    branches: [ main, DEV, QA, PROD ]
  pull_request:
    branches: [ main, DEV, QA, PROD ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build & Test
        run: mvn -B -q clean test